apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api-service

spec:
  type: NodePort
  selector:
    app: spring-boot-api

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
