name: CI Tests

on:
  workflow_call:
    inputs:
      full_tag:
        required: true
        type: string
    outputs:
      test_passed:
        value: ${{ jobs.tests.outputs.test_passed }}

jobs:
  tests:
    runs-on: ubuntu-latest

    outputs:
      test_passed: ${{ steps.result.outputs.test_passed }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"

      - name: Caching Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: run test
        id: run_test
        run: ./mvnw test
        continue-on-error: true
      - name: Result
        id: result
        run: |
          if [ "${{ steps.run_test.outcome }}" = "success" ]; then
            echo "test_passed=true" >> $GITHUB_OUTPUT
          else
            echo "test_passed=false" >> $GITHUB_OUTPUT
          fi
